### PR TITLE
Create Example-All.java

### PR DESCRIPTION
**Pull request by natanbc**

### CODE REVIEW

**Comment by MattIPv4** [comment]
~~Natan, could an example please be added for posting a guild count for a non-sharded bot?~~
Fixed, example is sharded.

**Comment by MattIPv4** [comment]
This also appears to use a non standard library to communicate the DBL. For examples we would like them to use more standard libraries in the language.

**Review by MattIPv4 — DISMISSED** [review]
This appears to make use a non standard library to communicate the DBL.
For examples we would like them to use more standard libraries within the language please.

**Comment by natanbc** [comment]
screenshot

**Review by MattIPv4 — CHANGES_REQUESTED** [review]
Could an example of posting bot stats every 30 mins in the background be added? This seems to be what DBL suggests now for posting.

**Review by MattIPv4 — APPROVED** [review]

**Review by MattIPv4 — CHANGES_REQUESTED** [review]
Could you please update https://github.com/MattIPv4/DiscordBots.org-API-Examples/blob/master/EXAMPLES.md to include a link to this with the correct title :)

**Review by MattIPv4 — APPROVED** [review]

**Pull request merged**
