### PR TITLE
Added Example for Javacord, using okHttp3

### PR DESCRIPTION
**Pull request by ghost**
Gradle Imports:
```gradle
    compile "com.squareup.okio:okio:1.13.0"
    compile 'com.squareup.okhttp3:okhttp:3.9.1'
```

Maven Imports:
```xml
<dependency>
    <groupId>com.squareup.okhttp3</groupId>
    <artifactId>okhttp</artifactId>
    <version>3.9.1</version>
</dependency>
<dependency>
    <groupId>com.squareup.okio</groupId>
    <artifactId>okio</artifactId>
    <version>1.13.0</version>
</dependency>
```

### CODE REVIEW

**Review by MattIPv4 — CHANGES_REQUESTED** [review]
~~* Please follow the correct file naming scheme in [CONTRIBUTING.md](https://github.com/MattIPv4/DiscordBots.org-API-Examples/blob/master/CONTRIBUTING.md)~~ Done
~~* Please leave all notes in the file provided, as comments~~ Done
~~* Please use the correct variable placeholders as found in [CONTRIBUTING.md](https://github.com/MattIPv4/DiscordBots.org-API-Examples/blob/master/CONTRIBUTING.md)~~ Done
* As this example uses a Discord API Library, please use that to provide the bot ID
* Remove any examples of this language/library combination from the [relevant to-be-processed file](https://github.com/MattIPv4/DiscordBots.org-API-Examples/blob/master/to-be-processed-java.txt)

**Comment by ghost** [comment]
grafik
i dont understand what you mean by that

**Comment by MattIPv4** [comment]
Don't get the user to fill in the bot ID manually, use the discord library (javacord) and automatically get the bot ID.

**Comment by ghost** [comment]
@MattIPv4 thats the Discord bot list id, what should be clear in the code tho. theres no way i could grab that from the javacord api :D

**Comment by ghost** [comment]
just noticed they are the same.

**Review by Repulser — COMMENTED** [review]
I would highlight that this is in a class, also you should only parse mediatype once?
Why are you including okio?

**Comment by MattIPv4** [comment]
Inactive for a long time.

**Pull request closed without merging**
