### PR TITLE
Add dblposter to javascript examples.

### PR DESCRIPTION
**Pull request by vladfrangu**
Hello.

I've made this PR to hopefully add my library, [dblposter](https://github.com/KingDGrizzle/dblposter) to the javascript examples directory.

I'm waiting for feedback, as my code comments might be too much, or don't exemplify anything.
I will also work on a ratelimit handler soon, to make sure bigger bots that (might) use this library won't get blocked due to all shards trying to post. But right now, the stats are posted every 2 minutes. I can also increate that timer, if needed.

Thanks for your time!

### CODE REVIEW

**Comment by MattIPv4** [comment]
Your library does not follow the standards for posting stats.
Stats should be posted every thirty (30) minutes as a background task.

**Comment by vladfrangu** [comment]
I was about to say that I will make it run every 30 minutes, but then how would I go about this PR? Would I remake it or ask for it to be reopened?

**Comment by MattIPv4** [comment]
You can reopen it once the library does that. I'd also add comments explaining how to manually trigger a stats post using your lib.

**Comment by vladfrangu** [comment]
Hello. I'm almost ready to release 1.3.0, doing all the required changes + some internal refactoring (with testing before hand), but I've stumbled on a semi road block. You said to document a way for the user to manually trigger a stats post using my lib.
Does that require the user to manually input said data or is it ok if the user runs a function say `post`, that will do everything for them? I think the latter is the easiest on the end user (which is one of the main goals for my lib)

Also, I cannot reopen the PR as you closed it. If i was the one closing it, I would be able to.

**Comment by MattIPv4** [comment]
Just a method to trigger it, so it can use data you fetch like you would for the background loop posting. Lmk once it's ready to go and I'll reopen + merge.

**Comment by vladfrangu** [comment]
As of [this release on GitHub](https://github.com/KingDGrizzle/dblposter/releases/tag/v1.3.0), and the new npm release, I have implemented everything as requested.
* Stats posting happens every 30 minutes
* Stat posting has a 1.5 second delay before actually sending, in case someone has a lot of shards which want to post data
* You can manually run a post, but it will reset the internal timer

Let me know if anything else is wrong, otherwise, it is ready to go!

**Comment by vladfrangu** [comment]
Sorry for the re-ping, but @MattIPv4 I've done your requested changes, as seen above. 😄

**Review by MattIPv4 — CHANGES_REQUESTED** [review]
Can you add this example to EXAMPLES.md please

**Comment by vladfrangu** [comment]
Done @MattIPv4. Aded the example in the examples markdown file

**Review by MattIPv4 — APPROVED** [review]

**Pull request merged**
